name: Build windows Executable

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use GitHub's macOS runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build the macOS executable using PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --add-data "images/*;images" --name=my_app_name main.p

        # The built executable will be in the `dist` directory

      # Step 5: Archive the build artifacts (optional)
      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/  # Upload the dist folder with the .app file
